version: '3.8'

services:
  go-commerce:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    restart: always
    image: "postgres:latest"
    environment:
      DATABASE_USER: postgres
      POSTGRES_PASSWORD: postgres
